// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 17 Sep 2022 12:41:59 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package decklink

/*
#cgo darwin CFLAGS: -framework CoreFoundation
#cgo darwin LDFLAGS: -framework CoreFoundation
#include <stdint.h>
#include <<CoreFoundation/CoreFoundation.h>>
#include "DeckLinkAPI.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()

const ()
