// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 17 Sep 2022 14:28:28 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package Decklink provides go bindings for the Blackmagic Decklink SDK
*/
package decklink
