// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 17 Sep 2022 14:28:28 BST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package decklink

/*
#include <stdint.h>
#include "DeckLinkAPI.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

//  type as declared in include/DeckLinkAPI.h:104
type  uint32































































